// Récuéprer tous les utilisateurs .getAllUsers
GET  http://localhost:3000/user HTTP/1.1

###
// Ajouter un utilisateur .createOneUser
POST  http://localhost:3000/user HTTP/1.1
Content-Type: application/json

{
  "lastname": "Aminos",
  "firstname": "Nodormir",
  "pseudo": "jaimelesbonssteaks",
  "birthdate": "1999-05-10",
  "address": "",
  "zip_code": "",
  "city": "taboulistan",
  "phone_number": "",
  "email": "qsd@ilqdqsdfa.com",
  "password": "houmouss"
}

 // erreur sans les quotes alors que c'est du int

###
// Récupérer les infos d'un utilisateur par son ID .getOneUserById
GET http://localhost:3000/user/1 HTTP/1.1

###
// Modifier les infos d'un utilisateur par son ID .getOneUserById
PUT  http://localhost:3000/user/5 HTTP/1.1
Content-Type: application/json

{
  "lastname": "Olivier",
  "firstname": "Séné",
  "pseudo": "Olivier_Fan2Rock",
  "birthdate": "1941-05-10",
  "address": "",
  "zip_code": "",
  "city": "London",
  "phone_number": "",
  "email": "qsdqsqsdqsdfsdqsd@ilqdqsdfa.com",
  "password": "TelegraphRoad"
  }


###
// Supprimer un utilisateur .removeOneUserById
DELETE  http://localhost:3000/user/5 HTTP/1.1