// Récuéprer tous les utilisateurs .getAllUsers
GET  http://localhost:3000/user HTTP/1.1

###
// Ajouter un utilisateur .createOneUser
POST  http://localhost:3000/user HTTP/1.1
Content-Type: application/json

{
  "lastname": "Emmanuel",
  "firstname": "Macron",
  "pseudo": "vivela",
  "birthdate": "1901-05-10",
  "address": "",
  "zip_code": "",
  "city": "Tunis",
  "phone_number": "",
  "email": "lolololo@ilfa.com",
  "password": "jmJeanLuc<3"
}

 // erreur sans les quotes alors que c'est du int

###
// Récupérer les infos d'un utilisateur par son ID .getOneUserById
GET http://localhost:3000/user/1 HTTP/1.1

###
// Modifier les infos d'un utilisateur par son ID .getOneUserById
PUT  http://localhost:3000/user/5 HTTP/1.1
Content-Type: application/json

{
  "lastname": "lolo",
  "firstname": "Macroute",
  "pseudo": "jEsUiSLePrEsiDeNt gngngna",
  "birthdate": "1945-05-10",
  "address": "",
  "zip_code": "",
  "city": "",
  "phone_number": "",
  "email": "lolololo@ila.com",
  "password": "cornin18"
}
###
// Modifie les droits (rôle) d'un utilisateur par son ID .adminModifyOneUserById
PUT  http://localhost:3000/user/admin/5 HTTP/1.1
Content-Type: application/json

{
  "lastname": "Emmanuel",
  "firstname": "Macroute",
  "pseudo": "jEsUiSLePrEsiDeNt gngngna",
  "birthdate": "1945-05-10",
  "address": "",
  "zip_code": "",
  "city": "",
  "phone_number": "",
  "email": "lolololo@ila.com",
  "password": "cornin18",
  "role_id" : 2
}


###
// Supprimer un utilisateur .removeOneUserById
DELETE  http://localhost:3000/user/5 HTTP/1.1