// Récuéprer tous les utilisateurs .getAllUsers
GET  http://localhost:3000/user HTTP/1.1

###
// Ajouter un utilisateur .createOneUser
POST  http://localhost:3000/user HTTP/1.1
Content-Type: application/json

{
  "pseudo": "sdfqsdqsd",
  "email": "test@laposte.net",
  "password": "Houmous$1",
  "passwordConfirmation":"Houmous$1"
  }

 // erreur sans les quotes alors que c'est du int

###
// Récupérer les infos d'un utilisateur par son ID .getOneUserById
GET http://localhost:3000/user/1 HTTP/1.1

###
// Modifier les infos d'un utilisateur par son ID .getOneUserById
PUT   http://localhost:3000/user/10 HTTP/1.1
Content-Type: application/json

{
  "lastname": "jeanmichel",
  "firstname": "codeur",
  "pseudo": "sdfqsdqsd",
  "birthdate": "",
  "address": "",
  "zip_code": "15155",
  "city": "",
  "phone_number": ""
  }


###

// Modifier les infos d'un utilisateur par son ID .getOneUserById
PATCH    http://localhost:3000/user/10 HTTP/1.1
Content-Type: application/json

{
  "email": "qslmdjkqslmdj@lksd.com"
  }


###
// Supprimer un utilisateur .removeOneUserById
DELETE  http://localhost:3000/user/10 HTTP/1.1